version: '2.2'

services:
  eclipse-theia:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - 53000:3000
    volumes:
      - ./project:/home/project/:cached